use std::{any::Any, fmt::Debug};

use super::{structt::CPopulatedStruct, substitution::Substitutions, variable::CVariable};
use crate::{
    environment::{
        dependencies::DepResult,
        discover_equality::{DeqPriority, DeqResult, DeqSide, Equal},
        CheckResult, Environment,
    },
    resolvable::BoxedResolvable,
    scope::Scope,
    shared::{AnyEq, Id, Pool},
};

#[derive(Debug)]
pub enum ItemDefinition<'x> {
    Other(ItemId),
    Resolved(BoxedConstruct),
    Unresolved(BoxedResolvable<'x>),
}

impl<'x> ItemDefinition<'x> {
    pub fn is_placeholder(&self) -> bool {
        match self {
            Self::Unresolved(resolvable) => resolvable.is_placeholder(),
            _ => false,
        }
    }

    pub fn as_other(&self) -> Option<ItemId> {
        match self {
            &Self::Other(con) => Some(con),
            _ => None,
        }
    }

    pub fn as_resolved(&self) -> Option<&BoxedConstruct> {
        match self {
            Self::Resolved(con) => Some(con),
            _ => None,
        }
    }

    /// Returns `true` if the construct definition is [`Unresolved`].
    ///
    /// [`Unresolved`]: ConstructDefinition::Unresolved
    pub fn is_unresolved(&self) -> bool {
        matches!(self, Self::Unresolved(..))
    }
}

impl<'x> From<Box<dyn Construct>> for ItemDefinition<'x> {
    fn from(input: Box<dyn Construct>) -> Self {
        Self::Resolved(input)
    }
}

impl<'a, 'x> From<&'a ItemId> for ItemDefinition<'x> {
    fn from(input: &'a ItemId) -> Self {
        Self::Other(*input)
    }
}

impl<'x> From<ItemId> for ItemDefinition<'x> {
    fn from(input: ItemId) -> Self {
        Self::Other(input)
    }
}

#[derive(Debug)]
pub struct Item<'x> {
    pub definition: ItemDefinition<'x>,
    pub reduced: ItemDefinition<'x>,
    pub invariants: Option<Vec<crate::environment::invariants::Invariant>>,
    pub scope: Box<dyn Scope>,
    /// A dex that, when a value is plugged in for its first dependency, will
    /// evaluate to true if and only if the plugged in value could have been
    /// generated by this construct.
    pub from_dex: Option<ItemId>,
    pub name: Option<String>,
}

pub type ItemPool<'x> = Pool<Item<'x>, 'I'>;
pub type ItemId = Id<'I'>;

pub type GenInvResult = Vec<crate::environment::invariants::Invariant>;

pub type BoxedConstruct = Box<dyn Construct>;
pub trait Construct: Any + Debug + AnyEq {
    fn dyn_clone(&self) -> Box<dyn Construct>;

    #[allow(unused_variables)]
    fn check<'x>(
        &self,
        env: &mut Environment<'x>,
        this: ItemId,
        scope: Box<dyn Scope>,
    ) -> CheckResult {
        Ok(())
    }

    fn get_dependencies<'x>(&self, env: &mut Environment<'x>) -> DepResult;

    #[allow(unused_variables)]
    fn generated_invariants<'x>(
        &self,
        this: ItemId,
        env: &mut Environment<'x>,
    ) -> GenInvResult {
        vec![]
    }

    #[allow(unused_variables)]
    fn dereference(&self) -> Option<(ItemId, Option<&Substitutions>)> {
        None
    }

    #[allow(unused_variables)]
    fn discover_equality<'x>(
        &self,
        env: &mut Environment<'x>,
        self_subs: Vec<&Substitutions>,
        other_id: ItemId,
        other: &dyn Construct,
        other_subs: Vec<&Substitutions>,
        limit: u32,
    ) -> DeqResult {
        Ok(Equal::Unknown)
    }

    fn as_def<'x>(&self) -> ItemDefinition<'x> {
        ItemDefinition::Resolved(self.dyn_clone())
    }
}

pub fn downcast_construct<T: Construct>(from: &dyn Construct) -> Option<&T> {
    (from as &dyn Any).downcast_ref()
}

pub fn downcast_boxed_construct<T: Construct>(from: Box<dyn Construct>) -> Option<T> {
    (from as Box<dyn Any>).downcast().ok().map(|b| *b)
}

pub fn as_struct(from: &dyn Construct) -> Option<&CPopulatedStruct> {
    downcast_construct(from)
}

pub fn as_variable(from: &dyn Construct) -> Option<&CVariable> {
    downcast_construct(from)
}

#[macro_export]
macro_rules! impl_any_eq_for_construct {
    ($ConstructName:ident) => {
        impl crate::shared::AnyEq for $ConstructName {
            fn eq(&self, other: &dyn crate::shared::AnyEq) -> bool {
                (other as &dyn std::any::Any)
                    .downcast_ref::<Self>()
                    .map(|x| self == x)
                    .unwrap_or(false)
            }
        }
    };
}
